import entry from "./entry.js";

const json=(body,status=200)=>Response.json(body,{status,headers:{"cache-control":"no-store"}});
const MAX_COMMERCIAL_BODY_BYTES=32768;
function constantTimeEqual(a,b){a=String(a||"");b=String(b||"");if(a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i++)diff|=a.charCodeAt(i)^b.charCodeAt(i);return diff===0}
function authenticate(request,env){const h=request.headers.get("authorization")||"";if(!h.startsWith("Bearer "))return{ok:false,status:401,error:"UNAUTHORIZED"};if(!env.ADMIN_GPT_TOKEN)return{ok:false,status:503,error:"ADMIN_TOKEN_NOT_CONFIGURED"};return constantTimeEqual(h.slice(7).trim(),env.ADMIN_GPT_TOKEN)?{ok:true}:{ok:false,status:401,error:"UNAUTHORIZED"}}
function fail(message,status=400,details){throw Object.assign(new Error(message),{status,details})}
async function strictJson(request,allowed){const declared=Number(request.headers.get("content-length")||0);if(declared>MAX_COMMERCIAL_BODY_BYTES)fail("BODY_TOO_LARGE",413);const raw=await request.text();if(new TextEncoder().encode(raw).length>MAX_COMMERCIAL_BODY_BYTES)fail("BODY_TOO_LARGE",413);let body={};try{body=raw?JSON.parse(raw):{}}catch{fail("INVALID_REQUEST",400)}if(!body||typeof body!=="object"||Array.isArray(body))fail("INVALID_REQUEST",400);for(const k of Object.keys(body))if(!allowed.has(k))fail("UNKNOWN_FIELD",400,{field:k});return body}
function digest(v){const s=String(v||"").trim().toLowerCase();if(!/^[a-f0-9]{64}$/.test(s))fail("INVALID_SOURCE_DIGEST",400);return s}
function finite(v,name,min,max){const n=Number(v);if(!Number.isFinite(n)||n<min||n>max)fail("INVALID_REQUEST",400,{field:name});return n}
function share(v,name){if(v===undefined||v===null)return undefined;let n=finite(v,name,0,100);if(n>1)n/=100;return n}
function commercialInput(body){
  const receipts=body.source_receipts;if(!Array.isArray(receipts)||receipts.length<2||receipts.length>12)fail("SOURCE_RECEIPTS_REQUIRED",400,{min:2,max:12});
  const source_receipts=receipts.map((r,i)=>{if(!r||typeof r!=="object"||Array.isArray(r))fail("INVALID_SOURCE_RECEIPT",400,{index:i});for(const k of Object.keys(r))if(!["source","digest_sha256","result_digest"].includes(k))fail("UNKNOWN_SOURCE_RECEIPT_FIELD",400,{index:i,field:k});const source=String(r.source||"").trim().slice(0,80);if(!source)fail("INVALID_SOURCE_RECEIPT",400,{index:i});return{source,digest_sha256:digest(r.digest_sha256||r.result_digest)}});
  const rings=body.rings;if(!Array.isArray(rings)||rings.length<1||rings.length>5)fail("INVALID_TRADE_AREA_RINGS",400,{min:1,max:5});let lastRadius=0,lastPopulation=0;
  const allowed=new Set(["radius_m","population","area_km2","working_age_share","poi_total","competitor_count","transit_count","nearest_transit_walk_min","traffic_status"]);
  const normalized=rings.map((r,i)=>{if(!r||typeof r!=="object"||Array.isArray(r))fail("INVALID_RING",400,{index:i});for(const k of Object.keys(r))if(!allowed.has(k))fail("UNKNOWN_RING_FIELD",400,{index:i,field:k});const radius_m=finite(r.radius_m,`rings[${i}].radius_m`,1,10000),population=finite(r.population,`rings[${i}].population`,0,100000000),area_km2=finite(r.area_km2,`rings[${i}].area_km2`,0.000001,350);if(radius_m<=lastRadius)fail("RING_RADIUS_MUST_INCREASE",400,{index:i});if(population<lastPopulation)fail("CUMULATIVE_POPULATION_MUST_NOT_DECREASE",400,{index:i});lastRadius=radius_m;lastPopulation=population;const out={radius_m,population,area_km2};const working=share(r.working_age_share,`rings[${i}].working_age_share`);if(working!==undefined)out.working_age_share=working;if(r.poi_total!==undefined)out.poi_total=finite(r.poi_total,`rings[${i}].poi_total`,0,1000000);if(r.competitor_count!==undefined)out.competitor_count=finite(r.competitor_count,`rings[${i}].competitor_count`,0,100000);if(r.transit_count!==undefined)out.transit_count=finite(r.transit_count,`rings[${i}].transit_count`,0,100000);if(r.nearest_transit_walk_min!==undefined)out.nearest_transit_walk_min=finite(r.nearest_transit_walk_min,`rings[${i}].nearest_transit_walk_min`,0,240);if(r.traffic_status!==undefined)out.traffic_status=Math.trunc(finite(r.traffic_status,`rings[${i}].traffic_status`,0,4));return out});
  const task_id=body.task_id===undefined?`commercial-spatial-${crypto.randomUUID()}`:String(body.task_id||"").trim();if(!/^[A-Za-z0-9._:-]{1,160}$/.test(task_id))fail("INVALID_TASK_ID",400);
  return{task_id,source_receipts,rings:normalized};
}

function literatureActionPath(){return{post:{operationId:"runLiteratureProductionSelftest",summary:"Verify live OpenAlex, Semantic Scholar, and BASE production keys",description:"Run one bounded live search against OpenAlex, Semantic Scholar, and BASE through the intelligence service binding. Returns per-provider PASS/FAIL without exposing API keys.",security:[{BearerAuth:[]}],requestBody:{required:false,content:{"application/json":{schema:{type:"object",additionalProperties:false}}}},responses:{"200":{description:"All three live keyed providers passed with non-empty results."},"401":{description:"Unauthorized."},"503":{description:"One or more production keys/providers failed, or the intelligence binding is unavailable."}}}}}
function providerActionPath(){return{post:{operationId:"runProviderFreshE2E",summary:"Run fresh Google, PKULaw, and Wind AIFin production E2E",description:"Authenticated zero-AI canary through the intelligence service binding for the approved provider set: BigQuery, Earth Engine, Google Patents, PKULaw, and Wind AIFin. Returns only redacted receipts and does not expose credentials.",security:[{BearerAuth:[]}],requestBody:{required:false,content:{"application/json":{schema:{type:"object",additionalProperties:false}}}},responses:{"200":{description:"All provider canaries passed with fresh runtime receipts."},"401":{description:"Unauthorized."},"503":{description:"One or more provider canaries failed, timed out, or the intelligence binding is unavailable."}}}}}
function commercialActionPath(){return{post:{operationId:"runCommercialSpatialFusion",summary:"Run bounded free-data commercial spatial fusion",description:"Dispatch a fixed CPU/GIS commercial-spatial recipe through the compute service binding. Accepts only bounded rings and SHA-256 source receipts; no model, provider, URL, code, GPU, or network controls are exposed.",security:[{BearerAuth:[]}],requestBody:{required:true,content:{"application/json":{schema:{type:"object",additionalProperties:false,required:["rings","source_receipts"],properties:{task_id:{type:"string",minLength:1,maxLength:160,pattern:"^[A-Za-z0-9._:-]+$"},source_receipts:{type:"array",minItems:2,maxItems:12,items:{type:"object",additionalProperties:false,required:["source"],properties:{source:{type:"string",minLength:1,maxLength:80},digest_sha256:{type:"string",pattern:"^[A-Fa-f0-9]{64}$"},result_digest:{type:"string",pattern:"^[A-Fa-f0-9]{64}$"}}}},rings:{type:"array",minItems:1,maxItems:5,items:{type:"object",additionalProperties:false,required:["radius_m","population","area_km2"],properties:{radius_m:{type:"number",exclusiveMinimum:0,maximum:10000},population:{type:"number",minimum:0,maximum:100000000},area_km2:{type:"number",exclusiveMinimum:0,maximum:350},working_age_share:{type:"number",minimum:0,maximum:100},poi_total:{type:"number",minimum:0},competitor_count:{type:"number",minimum:0},transit_count:{type:"number",minimum:0},nearest_transit_walk_min:{type:"number",minimum:0,maximum:240},traffic_status:{type:"integer",minimum:0,maximum:4}}}}}}}}},responses:{"202":{description:"Bounded Kaggle CPU task accepted and running."},"400":{description:"Invalid bounded commercial-spatial request."},"401":{description:"Unauthorized."},"409":{description:"Compute center is busy or task ID is duplicated."},"503":{description:"Compute binding or verified free compute route unavailable."}}}}}
function commercialStatusPath(){return{post:{operationId:"getCommercialSpatialFusionStatus",summary:"Read bounded commercial spatial task status",description:"Read or finalize one previously dispatched commercial-spatial task through the internal compute binding. Only a bounded task_id is accepted; no execution settings can be changed.",security:[{BearerAuth:[]}],requestBody:{required:true,content:{"application/json":{schema:{type:"object",additionalProperties:false,required:["task_id"],properties:{task_id:{type:"string",minLength:1,maxLength:160,pattern:"^[A-Za-z0-9._:-]+$"}}}}}},responses:{"200":{description:"Task reached a terminal state; result is returned when available."},"202":{description:"Task is queued or running."},"400":{description:"Invalid task_id."},"401":{description:"Unauthorized."},"404":{description:"Task not found."},"502":{description:"Upstream task failed."}}}}}

async function runLiteratureSelftest(request,env){const auth=authenticate(request,env);if(!auth.ok)return json({ok:false,error:auth.error,http_status:auth.status},auth.status);const svc=env.INTELLIGENCE_CENTER;if(!svc?.fetch)return json({ok:false,error:"CENTER_UNCONFIGURED",center:"intelligence",http_status:503},503);const started=Date.now(),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),65000);try{const r=await svc.fetch(new Request("https://intelligence.internal/v1/selftest/literature",{method:"POST",headers:{accept:"application/json","content-type":"application/json"},body:"{}",signal:controller.signal}));const body=await r.json().catch(()=>null),ok=r.ok&&body?.ok===true;return json({ok,http_status:r.status,center:"intelligence",suite:"literature-production-keys",business_e2e:body?.business_e2e===true,selftest:body,elapsed_ms:Date.now()-started},ok?200:(r.status||503))}catch(error){const timeout=error?.name==="AbortError";return json({ok:false,error:timeout?"SELFTEST_TIMEOUT":"SELFTEST_FAILED",center:"intelligence",suite:"literature-production-keys",message:String(error?.message||error).slice(0,200),http_status:timeout?504:502,elapsed_ms:Date.now()-started},timeout?504:502)}finally{clearTimeout(timer)}}
async function runProviderSelftest(request,env){const auth=authenticate(request,env);if(!auth.ok)return json({ok:false,error:auth.error,http_status:auth.status,ai_called:false},auth.status);const svc=env.INTELLIGENCE_CENTER;if(!svc?.fetch)return json({ok:false,error:"CENTER_UNCONFIGURED",center:"intelligence",suite:"provider-fresh-e2e",http_status:503,ai_called:false},503);const started=Date.now(),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),180000);try{const r=await svc.fetch(new Request("https://intelligence.internal/v1/selftest/providers",{method:"POST",headers:{accept:"application/json","content-type":"application/json"},body:"{}",signal:controller.signal}));const body=await r.json().catch(()=>null),ok=r.ok&&body?.ok===true;return json({ok,http_status:r.status,center:"intelligence",suite:"provider-fresh-e2e",business_e2e:true,ai_called:false,bigquery_query_scan:body?.bigquery_query_scan===true,bigquery_bytes_billed:body?.bigquery_bytes_billed??null,receipt_digest:body?.receipt_digest||null,checks:Array.isArray(body?.checks)?body.checks:[],observed_at:body?.observed_at||null,secrets_redacted:true,elapsed_ms:Date.now()-started},ok?200:(r.status||503))}catch(error){const timeout=error?.name==="AbortError";return json({ok:false,error:timeout?"SELFTEST_TIMEOUT":"SELFTEST_FAILED",center:"intelligence",suite:"provider-fresh-e2e",message:String(error?.message||error).slice(0,200),http_status:timeout?504:502,ai_called:false,elapsed_ms:Date.now()-started},timeout?504:502)}finally{clearTimeout(timer)}}
async function runCommercialSpatial(request,env){const auth=authenticate(request,env);if(!auth.ok)return json({ok:false,error:auth.error,http_status:auth.status},auth.status);const svc=env.COMPUTE_CENTER;if(!svc?.fetch)return json({ok:false,error:"CENTER_UNCONFIGURED",center:"compute",http_status:503},503);try{const input=commercialInput(await strictJson(request,new Set(["task_id","source_receipts","rings"]))),payload={task_id:input.task_id,profile:"gis",provider:"kaggle",timeout_seconds:300,gpu:false,input:{model_recipe:{model_id:"location_intelligence.commercial_spatial_fusion",args:{source_receipts:input.source_receipts,rings:input.rings}}}};const r=await svc.fetch(new Request("https://compute.internal/v1/run",{method:"POST",headers:{accept:"application/json","content-type":"application/json"},body:JSON.stringify(payload)})),body=await r.json().catch(()=>({ok:false,error:"COMPUTE_BAD_JSON"}));return json({ok:r.ok&&body?.ok===true,http_status:r.status,center:"compute",suite:"commercial-spatial-fusion",task_id:body?.task_id||input.task_id,status:body?.status||null,executor:body?.executor||null,machine_shape:body?.machine_shape||null,error:body?.error||null,message:body?.message||null,secrets_redacted:true},r.status)}catch(error){return json({ok:false,error:String(error?.message||"INVALID_REQUEST"),http_status:error?.status||400,details:error?.details||undefined},error?.status||400)}}
async function commercialSpatialStatus(request,env){const auth=authenticate(request,env);if(!auth.ok)return json({ok:false,error:auth.error,http_status:auth.status},auth.status);const svc=env.COMPUTE_CENTER;if(!svc?.fetch)return json({ok:false,error:"CENTER_UNCONFIGURED",center:"compute",http_status:503},503);try{const body=await strictJson(request,new Set(["task_id"])),task_id=String(body.task_id||"").trim();if(!/^[A-Za-z0-9._:-]{1,160}$/.test(task_id))fail("INVALID_TASK_ID",400);const r=await svc.fetch(new Request("https://compute.internal/v1/status",{method:"POST",headers:{accept:"application/json","content-type":"application/json"},body:JSON.stringify({task_id})})),out=await r.json().catch(()=>({ok:false,error:"COMPUTE_BAD_JSON"}));return json({...out,http_status:r.status,center:"compute",suite:"commercial-spatial-fusion",secrets_redacted:true},r.status)}catch(error){return json({ok:false,error:String(error?.message||"INVALID_REQUEST"),http_status:error?.status||400,details:error?.details||undefined},error?.status||400)}}

async function openApi(request,env,ctx){const response=await entry.fetch(request,env,ctx);if(!response.ok)return response;const spec=await response.json();return json({...spec,paths:{...(spec.paths||{}),"/v1/intelligence/literature-selftest":literatureActionPath(),"/v1/intelligence/provider-selftest":providerActionPath(),"/v1/compute/commercial-spatial":commercialActionPath(),"/v1/compute/commercial-spatial/status":commercialStatusPath()}})}

export default{async fetch(request,env,ctx){const url=new URL(request.url);if(request.method==="POST"&&url.pathname==="/v1/intelligence/literature-selftest")return runLiteratureSelftest(request,env);if(request.method==="POST"&&url.pathname==="/v1/intelligence/provider-selftest")return runProviderSelftest(request,env);if(request.method==="POST"&&url.pathname==="/v1/compute/commercial-spatial")return runCommercialSpatial(request,env);if(request.method==="POST"&&url.pathname==="/v1/compute/commercial-spatial/status")return commercialSpatialStatus(request,env);if(request.method==="GET"&&url.pathname==="/openapi.json")return openApi(request,env,ctx);return entry.fetch(request,env,ctx)}};
