import base,{AdminCoordinator} from "./index.js";
import {verifyBearer} from "./security.js";
export {AdminCoordinator};
const H={"content-type":"application/json;charset=utf-8","cache-control":"no-store"};
const json=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
const redact=v=>{if(Array.isArray(v))return v.map(redact);if(v&&typeof v==="object"){const o={};for(const[k,x]of Object.entries(v))o[k]=/token|secret|password|authorization|cookie|api.?key/i.test(k)?"[REDACTED]":redact(x);return o}return v};
const fail=(c,m,s=409,d)=>json({ok:false,error:c,message:m,...(d?{details:redact(d)}:{})},s);
function st(env){return env.ADMIN_COORDINATOR.get(env.ADMIN_COORDINATOR.idFromName("global"))}
async function sc(env,p,m="GET",d){const i={method:m,headers:{"content-type":"application/json"}};if(d!==undefined)i.body=JSON.stringify(d);const r=await st(env).fetch(new Request(`https://state.internal${p}`,i)),x=await r.json().catch(()=>({ok:false,error:"STATE_BAD_RESPONSE"}));if(!r.ok)throw Object.assign(new Error(x.error||"STATE_ERROR"),{status:r.status,details:x});return x}
async function auth(req,env){if(!env.ADMIN_GPT_TOKEN)throw Object.assign(new Error("ADMIN_TOKEN_NOT_CONFIGURED"),{status:503});if(!await verifyBearer(req,env.ADMIN_GPT_TOKEN))throw Object.assign(new Error("UNAUTHORIZED"),{status:401})}
async function cf(env,p,init={}){if(!env.CF_ACCOUNT_ID||!env.CF_API_TOKEN)throw Object.assign(new Error("CF_API_NOT_CONFIGURED"),{status:503});const headers={authorization:`Bearer ${env.CF_API_TOKEN}`,accept:"application/json",...(init.headers||{})};if(init.body)headers["content-type"]="application/json";const r=await fetch(`https://api.cloudflare.com/client/v4/accounts/${env.CF_ACCOUNT_ID}${p}`,{...init,headers}),x=await r.json().catch(()=>null);if(!r.ok||x?.success===false)throw Object.assign(new Error("CLOUDFLARE_API_ERROR"),{status:502,details:x});return x}
async function current(env,s){const d=await cf(env,`/workers/scripts/${encodeURIComponent(s)}/deployments`),ds=d?.result?.deployments||d?.result||[];for(const dep of ds){const vs=dep?.versions||[],v=vs.find(x=>Number(x.percentage)===100)||vs[0];if(v?.version_id)return v.version_id}return null}
async function previous(env,s,cur){const d=await cf(env,`/workers/scripts/${encodeURIComponent(s)}/deployments`),ds=d?.result?.deployments||d?.result||[];for(const dep of ds.slice(1)){const vs=dep?.versions||[],v=vs.find(x=>Number(x.percentage)===100)||vs[0];if(v?.version_id&&v.version_id!==cur)return v.version_id}return null}
async function deployVersion(env,s,v,msg){return cf(env,`/workers/scripts/${encodeURIComponent(s)}/deployments`,{method:"POST",body:JSON.stringify({strategy:"percentage",versions:[{version_id:v,percentage:100}],annotations:{"workers/message":String(msg||"").slice(0,900)}})})}
function managed(env,s){const a=String(env.MANAGED_SCRIPTS||"admin-worker,governance-worker,intelligence-worker,compute-worker,expert-worker,maintenance-worker").split(",").map(x=>x.trim()).filter(Boolean);if(!a.includes(s))throw Object.assign(new Error("SCRIPT_NOT_MANAGED"),{status:403});return a}
function bind(env,n){return{governance:env.GOVERNANCE_CENTER,intelligence:env.INTELLIGENCE_CENTER,compute:env.COMPUTE_CENTER,expert:env.EXPERT_CENTER,maintenance:env.MAINTENANCE_CENTER}[n]||null}
function centerFor(s){return{"admin-worker":"admin","governance-worker":"governance","intelligence-worker":"intelligence","compute-worker":"compute","expert-worker":"expert","maintenance-worker":"maintenance"}[s]||null}
function pathsFor(n){if(n==="admin")return["/health","/v1/admin/capabilities","/v1/admin/context"];if(n==="maintenance")return["/health","/v1/maintenance/latest"];return["/health","/v1/policy","/v1/capabilities","/source"]}
async function probe(env,n,p){if(n==="admin"){try{const headers={accept:"application/json"};if(p!=="/health")headers.authorization=`Bearer ${env.ADMIN_GPT_TOKEN||""}`;const r=await base.fetch(new Request(`https://admin.internal${p}`,{headers}),env,{waitUntil(){}});return{ok:r.ok,http_status:r.status}}catch(e){return{ok:false,error:String(e?.message||e)}}}const b=bind(env,n);if(!b?.fetch)return{ok:false,error:"CENTER_UNCONFIGURED"};const c=new AbortController(),t=setTimeout(()=>c.abort(),8000);try{const r=await b.fetch(new Request(`https://${n}.internal${p}`,{headers:{accept:"application/json"},signal:c.signal}));return{ok:r.ok,http_status:r.status}}catch(e){return{ok:false,error:String(e?.message||e)}}finally{clearTimeout(t)}}
async function audit(env,r){try{await sc(env,"/audit","POST",{at:new Date().toISOString(),...redact(r)})}catch{}}
async function cancelled(env,id){const t=await sc(env,`/task/${encodeURIComponent(id)}`).catch(()=>({task:null}));return t.task?.cancel_requested===true}
async function release(env,owner){try{await sc(env,"/lock/release","POST",{owner})}catch{}}
async function rollbackIfActive(env,snap,reason){try{const cur=await current(env,snap.script);if(cur!==snap.version_id)return{ok:true,skipped:true,reason:"production_moved",current:cur};const target=snap.base_version||await previous(env,snap.script,cur);if(!target||target===snap.version_id)return{ok:false,skipped:true,reason:"rollback_target_unavailable",current:cur};const d=await deployVersion(env,snap.script,target,`Automatic fail-closed rollback: ${reason}`);await audit(env,{action:"guard.rollback.auto",script:snap.script,from:snap.version_id,to:target,reason});return{ok:true,rolled_back:true,from:snap.version_id,to:target,deployment:redact(d?.result||d)}}catch(e){await audit(env,{action:"guard.rollback.failed",script:snap.script,version_id:snap.version_id,reason,error:String(e?.message||e)});return{ok:false,error:String(e?.message||e)}}}
async function createCandidate(req,env){await auth(req,env);const b=await req.json().catch(()=>({})),script=String(b.script||""),version=String(b.version_id||"");if(!script||!version)return fail("INVALID_REQUEST","script and version_id required",400);managed(env,script);const cur=await current(env,script);if(cur!==version)return fail("CANDIDATE_VERSION_MISMATCH","With Git Integration, candidate must be the currently active build version",409,{active_version:cur,candidate_version:version});const prev=await previous(env,script,cur);if(b.base_version&&prev&&String(b.base_version)!==String(prev))return fail("ROLLBACK_BASE_MISMATCH","base_version does not match previous stable deployment",409,{previous_version:prev});const c={script,version_id:version,base_version:prev||null,change_summary:String(b.change_summary||"").slice(0,2000),created_at:new Date().toISOString(),deployment_model:"post-deploy-verify",validated:false,approved:false,test_passed:false};await sc(env,"/candidate","POST",c);await audit(env,{action:"guard.candidate.create",script,version_id:version,base_version:c.base_version});return json({ok:true,candidate:c},201)}
async function runAcceptance(env,id,center,suite,owner,snap){let rollback=null;try{await sc(env,`/task/${encodeURIComponent(id)}`,"POST",{id,status:"running",center,suite,candidate:snap,started_at:new Date().toISOString()});const names=center==="all"?["admin","governance","intelligence","compute","expert","maintenance"]:[center],checks=[];for(const n of names){for(const p of pathsFor(n)){if(await cancelled(env,id))throw new Error("CANCELLED");checks.push({center:n,path:p,...await probe(env,n,p)})}}const end=await current(env,snap.script);checks.push({name:"candidate-version-still-active",ok:end===snap.version_id,expected:snap.version_id,actual:end});const ok=checks.every(x=>x.ok);if(!ok)rollback=await rollbackIfActive(env,snap,"acceptance_failed");const material=JSON.stringify({run_id:id,candidate:snap,checks,rollback}),h=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(material)),digest=[...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,"0")).join(""),rec={run_id:id,status:ok?"pass":"fail",suite,center,candidate:snap,runtime_tested:true,receipt_digest:digest,rollback,finished_at:new Date().toISOString()};await sc(env,`/task/${encodeURIComponent(id)}`,"POST",{...rec,checks});await sc(env,`/acceptance/${encodeURIComponent(center)}`,"POST",rec);const c=(await sc(env,"/candidate")).candidate;if(c?.script===snap.script&&c?.version_id===snap.version_id)await sc(env,"/candidate","POST",{...c,test_passed:ok,last_acceptance_run_id:id,last_acceptance_receipt:digest,last_acceptance_at:rec.finished_at,...(rollback?.rolled_back?{rolled_back:true,rolled_back_to:rollback.to,rolled_back_at:rec.finished_at}:{})});await audit(env,{action:"guard.acceptance.finish",run_id:id,ok,candidate:snap,rollback})}catch(e){rollback=await rollbackIfActive(env,snap,String(e.message)==="CANCELLED"?"acceptance_cancelled":"acceptance_error");await sc(env,`/task/${encodeURIComponent(id)}`,"POST",{status:String(e.message)==="CANCELLED"?"cancelled":"fail",error:String(e.message),rollback,finished_at:new Date().toISOString()}).catch(()=>{});await audit(env,{action:"guard.acceptance.error",run_id:id,error:String(e.message),candidate:snap,rollback})}finally{await release(env,owner)}}
async function startTest(req,env,ctx){await auth(req,env);const b=await req.json().catch(()=>({})),center=String(b.center||"all"),suite=String(b.suite||"contract"),id=String(b.request_id||crypto.randomUUID()),allowed=["all","admin","governance","intelligence","compute","expert","maintenance"];if(!allowed.includes(center))return fail("INVALID_REQUEST","Invalid center",400);const old=await sc(env,`/task/${encodeURIComponent(id)}`).catch(()=>({task:null}));if(old.task)return json({ok:true,reused:true,run_id:id,status:old.task.status||"unknown",task:old.task});const c=(await sc(env,"/candidate")).candidate;if(!c||!c.validated)return fail("CANDIDATE_NOT_VALIDATED","Create and validate candidate first",409);const cc=centerFor(c.script);if(center!=="all"&&cc&&center!==cc)return fail("CENTER_CANDIDATE_MISMATCH","Acceptance center does not match candidate",409,{candidate_center:cc});const cur=await current(env,c.script);if(cur!==c.version_id)return fail("CANDIDATE_VERSION_MISMATCH","Candidate is not the active Worker version",409,{active_version:cur,candidate_version:c.version_id});const snap={script:c.script,version_id:c.version_id,base_version:c.base_version||null,validated_at:c.validated_at||null,started_active_version:cur},owner=`test:${id}`;await sc(env,"/lock/acquire","POST",{owner,kind:"acceptance",ttl_seconds:1800});await sc(env,`/task/${encodeURIComponent(id)}`,"POST",{id,status:"accepted",center,suite,candidate:snap,accepted_at:new Date().toISOString()});ctx.waitUntil(runAcceptance(env,id,center,suite,owner,snap));return json({ok:true,run_id:id,status:"accepted",candidate:snap},202)}
async function promote(req,env){await auth(req,env);const b=await req.json().catch(()=>({})),c=(await sc(env,"/candidate")).candidate;if(!c)return fail("NO_CANDIDATE","No candidate",404);if(!c.validated||!c.approved||!c.test_passed)return fail("CANDIDATE_NOT_READY","Candidate must be validated, approved and acceptance-tested",409);const center=String(b.center||"all"),a=(await sc(env,`/acceptance/${encodeURIComponent(center)}`).catch(()=>({acceptance:null}))).acceptance;if(!a||a.status!=="pass"||a.runtime_tested!==true)return fail("ACCEPTANCE_REQUIRED","Passing bound runtime acceptance required",409);if(a.candidate?.script!==c.script||a.candidate?.version_id!==c.version_id)return fail("ACCEPTANCE_VERSION_MISMATCH","Acceptance does not belong to this candidate",409,{accepted_candidate:a.candidate,current_candidate:{script:c.script,version_id:c.version_id}});if(b.acceptance_run_id&&String(b.acceptance_run_id)!==String(a.run_id))return fail("ACCEPTANCE_RUN_MISMATCH","acceptance_run_id does not match",409,{latest_run_id:a.run_id});const cur=await current(env,c.script);if(cur!==c.version_id)return fail("CANDIDATE_VERSION_MISMATCH","Tested candidate is no longer active",409,{active_version:cur,candidate_version:c.version_id});if(b.expected_current_version&&String(b.expected_current_version)!==String(cur))return fail("VERSION_CONFLICT","Production moved",409,{current:cur});const rollback=c.base_version||await previous(env,c.script,cur),nc={...c,promoted:true,promoted_at:new Date().toISOString(),accepted_run_id:a.run_id,accepted_receipt:a.receipt_digest||null,production_version:cur,rollback_target:rollback||null};await sc(env,"/candidate","POST",nc);await audit(env,{action:"guard.deploy.accept-active",script:c.script,version_id:cur,acceptance_run_id:a.run_id,rollback_target:nc.rollback_target});return json({ok:true,already_active:true,deployment_model:"post-deploy-verify",production_version:cur,acceptance_run_id:a.run_id,receipt_digest:a.receipt_digest||null,rollback_target:nc.rollback_target})}
export default{async fetch(req,env,ctx){try{const u=new URL(req.url);if(req.method==="POST"&&u.pathname==="/v1/admin/candidate")return await createCandidate(req,env);if(req.method==="POST"&&u.pathname==="/v1/admin/test")return await startTest(req,env,ctx);if(req.method==="POST"&&u.pathname==="/v1/admin/deploy/promote")return await promote(req,env);return await base.fetch(req,env,ctx)}catch(e){await audit(env,{action:"guard.error",path:new URL(req.url).pathname,error:String(e?.message||e)});return fail(String(e?.message||"INTERNAL_ERROR"),e?.status>=500?"Internal operation failed":String(e?.message||"Request failed"),e?.status||500,e?.details)}}};
