import guard,{AdminCoordinator} from "./guard.js";
import {PROTECTION_VERSION,protectionBaseline,verifyProtection} from "./protection.js";
import {verifyBearer} from "./security.js";
export {AdminCoordinator};
const H={"content-type":"application/json;charset=utf-8","cache-control":"no-store"};
const json=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
const fail=(c,m,s=409,d)=>json({ok:false,error:c,message:m,...(d?{details:d}:{})},s);
async function auth(req,env){if(!env.ADMIN_GPT_TOKEN)throw Object.assign(new Error("ADMIN_TOKEN_NOT_CONFIGURED"),{status:503});if(!await verifyBearer(req,env.ADMIN_GPT_TOKEN))throw Object.assign(new Error("UNAUTHORIZED"),{status:401})}
function st(env){return env.ADMIN_COORDINATOR.get(env.ADMIN_COORDINATOR.idFromName("global"))}
function bind(env,n){return{intelligence:env.INTELLIGENCE_CENTER,compute:env.COMPUTE_CENTER,expert:env.EXPERT_CENTER}[n]||null}
async function sc(env,p,m="GET",d){const i={method:m,headers:{"content-type":"application/json"}};if(d!==undefined)i.body=JSON.stringify(d);const r=await st(env).fetch(new Request(`https://state.internal${p}`,i)),x=await r.json().catch(()=>({ok:false,error:"STATE_BAD_RESPONSE"}));if(!r.ok)throw Object.assign(new Error(x.error||"STATE_ERROR"),{status:r.status,details:x});return x}
async function audit(env,r){try{await sc(env,"/audit","POST",{at:new Date().toISOString(),...r})}catch{}}
async function cf(env,p,init={}){if(!env.CF_ACCOUNT_ID||!env.CF_API_TOKEN)throw Object.assign(new Error("CF_API_NOT_CONFIGURED"),{status:503});const headers={authorization:`Bearer ${env.CF_API_TOKEN}`,accept:"application/json",...(init.headers||{})};if(init.body)headers["content-type"]="application/json";const r=await fetch(`https://api.cloudflare.com/client/v4/accounts/${env.CF_ACCOUNT_ID}${p}`,{...init,headers}),x=await r.json().catch(()=>null);if(!r.ok||x?.success===false)throw Object.assign(new Error("CLOUDFLARE_API_ERROR"),{status:502,details:x});return x}
async function current(env,s){const d=await cf(env,`/workers/scripts/${encodeURIComponent(s)}/deployments`),ds=d?.result?.deployments||d?.result||[];for(const dep of ds){const vs=dep?.versions||[],v=vs.find(x=>Number(x.percentage)===100)||vs[0];if(v?.version_id)return v.version_id}return null}
async function rollbackProtected(env,c,reason){try{if(!c?.script||!c?.version_id||!c?.base_version)return{ok:false,skipped:true,reason:"rollback_target_unavailable"};const cur=await current(env,c.script);if(cur!==c.version_id)return{ok:true,skipped:true,reason:"production_moved",current:cur};const d=await cf(env,`/workers/scripts/${encodeURIComponent(c.script)}/deployments`,{method:"POST",body:JSON.stringify({strategy:"percentage",versions:[{version_id:c.base_version,percentage:100}],annotations:{"workers/message":`Protected-core rollback: ${String(reason).slice(0,500)}`}})});await audit(env,{action:"protection.rollback.auto",script:c.script,from:c.version_id,to:c.base_version,reason});return{ok:true,rolled_back:true,from:c.version_id,to:c.base_version,deployment:d?.result||d}}catch(e){await audit(env,{action:"protection.rollback.failed",script:c?.script,version_id:c?.version_id,error:String(e?.message||e)});return{ok:false,error:String(e?.message||e)}}}
async function validateProtected(req,env,ctx){const baseResp=await guard.fetch(req,env,ctx);if(!baseResp.ok)return baseResp;const c=(await sc(env,"/candidate")).candidate;if(!c)return fail("NO_CANDIDATE","No candidate",404);const p=await verifyProtection(env,guard);if(p.ok){const nc={...c,validated:true,protection_passed:true,protection_version:PROTECTION_VERSION,protection_checked_at:new Date().toISOString()};await sc(env,"/candidate","POST",nc);await audit(env,{action:"protection.validate.pass",script:c.script,version_id:c.version_id,protection_version:PROTECTION_VERSION});return json({ok:true,candidate:nc,protection:{ok:true,version:PROTECTION_VERSION}})}const rollback=await rollbackProtected(env,c,"protected_runtime_invariant_changed");const nc={...c,validated:false,approved:false,test_passed:false,protection_passed:false,protection_version:PROTECTION_VERSION,protection_checked_at:new Date().toISOString(),protection_failure:p.checks.filter(x=>!x.ok),rollback};await sc(env,"/candidate","POST",nc);await audit(env,{action:"protection.validate.fail",script:c.script,version_id:c.version_id,failures:nc.protection_failure,rollback});return fail("PROTECTED_CORE_CHANGED","Candidate changed protected runtime invariants",409,{protection_version:PROTECTION_VERSION,failures:nc.protection_failure,rollback})}
async function centerSelftest(req,env){
  await auth(req,env);
  const b=await req.json().catch(()=>({})),center=String(b.center||"");
  if(!["intelligence","compute","expert"].includes(center))return fail("INVALID_REQUEST","center must be intelligence, compute, or expert",400);
  if(center==="expert"&&b.allow_paid!==true)return fail("PAID_CONFIRMATION_REQUIRED","Expert selftest makes a minimal paid OpenRouter call; set allow_paid=true explicitly",409);
  const svc=bind(env,center);if(!svc?.fetch)return fail("CENTER_UNCONFIGURED",`${center} service binding is not configured`,503);
  const started=Date.now();
  try{
    const c=new AbortController(),timer=setTimeout(()=>c.abort(),center==="expert"?150000:45000);
    try{
      const r=await svc.fetch(new Request(`https://${center}.internal/v1/selftest`,{method:"POST",headers:{accept:"application/json","content-type":"application/json"},body:"{}",signal:c.signal})),body=await r.json().catch(()=>null),ok=r.ok&&body?.ok===true;
      await audit(env,{action:"center.selftest",center,ok,http_status:r.status,business_e2e:body?.business_e2e===true,selftest_level:body?.selftest_level||null,elapsed_ms:Date.now()-started});
      return json({ok,center,http_status:r.status,business_e2e:body?.business_e2e===true,selftest:body,elapsed_ms:Date.now()-started},ok?200:(r.status||503));
    }finally{clearTimeout(timer)}
  }catch(e){await audit(env,{action:"center.selftest.error",center,error:String(e?.message||e)});return fail(e?.name==="AbortError"?"SELFTEST_TIMEOUT":"SELFTEST_FAILED",String(e?.message||e),e?.name==="AbortError"?504:502,{center,elapsed_ms:Date.now()-started})}
}
export default{async fetch(req,env,ctx){try{const u=new URL(req.url);if(req.method==="GET"&&u.pathname==="/v1/admin/protection"){await auth(req,env);const live=await verifyProtection(env,guard);return json({ok:live.ok,...protectionBaseline(),live})}if(req.method==="POST"&&u.pathname==="/v1/admin/selftest")return await centerSelftest(req,env);if(req.method==="POST"&&u.pathname==="/v1/admin/candidate/validate")return await validateProtected(req,env,ctx);return await guard.fetch(req,env,ctx)}catch(e){await audit(env,{action:"superguard.error",path:new URL(req.url).pathname,error:String(e?.message||e)});return fail(String(e?.message||"INTERNAL_ERROR"),e?.status>=500?"Internal operation failed":String(e?.message||"Request failed"),e?.status||500,e?.details)}}};
