const SERVICE="maintenance-worker",API_VERSION="2026-08-20.runtime-broker-v1";
const POLICY={scheduled_health_check:true,interval_minutes:15,read_only:true,auto_diagnose:true,consecutive_failure_tracking:true,acceptance_fail_closed_rollback:"admin-worker",automatic_code_upgrade:false,automatic_dependency_upgrade:false,protected_core_auto_upgrade:false,github_write:false,ai_gateway_control_read:true,cloudflare_credentials_local:false,control_plane_owner:"admin-worker"};
function json(x,s=200){return Response.json(x,{status:s,headers:{"cache-control":"no-store"}})}
function now(){return new Date().toISOString()}
function binding(env,n){return{governance:env.GOVERNANCE_CENTER,intelligence:env.INTELLIGENCE_CENTER,compute:env.COMPUTE_CENTER,expert:env.EXPERT_CENTER}[n]}
async function probe(env,n,path){const b=binding(env,n);if(!b?.fetch)return{ok:false,error:"UNBOUND"};const c=new AbortController(),t=setTimeout(()=>c.abort(),5000);try{const r=await b.fetch(new Request(`https://${n}.internal${path}`,{headers:{accept:"application/json"},signal:c.signal}));return{ok:r.ok,http_status:r.status}}catch{return{ok:false,error:"PROBE_FAILED"}}finally{clearTimeout(t)}}
function store(env){return env.MAINTENANCE_STATE.get(env.MAINTENANCE_STATE.idFromName("global"))}
async function ss(env,p,m="GET",b){const i={method:m,headers:{"content-type":"application/json"}};if(b!==undefined)i.body=JSON.stringify(b);const r=await store(env).fetch(new Request(`https://state.internal${p}`,i));return{http:r.status,...await r.json()}}
function constantTimeEqual(a,b){a=String(a||"");b=String(b||"");if(a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i++)diff|=a.charCodeAt(i)^b.charCodeAt(i);return diff===0}
function brokerFailureCode(error){const m=String(error?.message||error||"").toLowerCase();if(m.includes("timeout"))return"AI_GATEWAY_CONTROL_TIMEOUT";if(m.includes("entrypoint")||m.includes("not found"))return"AI_GATEWAY_CONTROL_ENTRYPOINT_UNAVAILABLE";if(m.includes("permission")||m.includes("forbidden")||m.includes("unauthorized")||m.includes("401")||m.includes("403"))return"AI_GATEWAY_CONTROL_PERMISSION";return"AI_GATEWAY_CONTROL_RPC_FAILED"}
function runtimeSecretPresence(env){return{canonical_account_configured:Boolean(String(env?.CF_ACCOUNT_ID||"").trim()),canonical_token_configured:Boolean(String(env?.CF_API_TOKEN||"").trim()),legacy_account_configured:Boolean(String(env?.CLOUDFLARE_ACCOUNT_ID||"").trim()),legacy_token_configured:Boolean(String(env?.CLOUDFLARE_AI_GATEWAY_API_TOKEN||"").trim()),secrets_redacted:true}}
async function probeAiGatewayControl(env){
  if(!env.AI_GATEWAY_CONTROL?.request)return{ok:false,binding:false,broker_rpc:false,routes_readable:false,error_code:"AI_GATEWAY_CONTROL_UNBOUND"};
  let timer;
  try{
    const timeout=new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error("AI_GATEWAY_CONTROL_TIMEOUT")),8000)});
    const payload=await Promise.race([env.AI_GATEWAY_CONTROL.request({operation:"routes.list"}),timeout]);
    const success=payload?.success!==false;
    return{ok:success,binding:true,broker_rpc:true,routes_readable:success,error_code:success?null:"AI_GATEWAY_CONTROL_READ_FAILED"};
  }catch(error){return{ok:false,binding:true,broker_rpc:false,routes_readable:false,error_code:brokerFailureCode(error)}}finally{if(timer)clearTimeout(timer)}
}
async function run(env,trigger){const owner=`${trigger}:${Math.floor(Date.now()/60000)}`,a=await ss(env,"/acquire","POST",{owner});if(!a.ok)return{ok:false,skipped:true,reason:"BUSY"};try{const before=(await ss(env,"/latest")).latest||null,checks=[];for(const n of ["governance","intelligence","compute","expert"]){for(const p of ["/health","/v1/policy","/v1/capabilities","/source"]){checks.push({center:n,path:p,...await probe(env,n,p)})}}const control_plane=await probeAiGatewayControl(env),ok=checks.every(x=>x.ok)&&control_plane.ok,failure_streak=ok?0:Math.max(0,Number(before?.failure_streak||0))+1,status=ok?"healthy":failure_streak===1?"degraded":"persistent_failure",failed_checks=checks.filter(x=>!x.ok),rec={ok,status,trigger,checked_at:now(),failure_streak,failed_checks,checks,control_plane,next_action:ok?"none":failure_streak===1?"retry_next_schedule":"admin_recovery_required",policy:POLICY,secrets_redacted:true};await ss(env,"/latest","POST",rec);return rec}finally{await ss(env,"/release","POST",{owner})}}
async function runtimeSelftest(req,env){
  const expected=String(env.MAINTENANCE_RUNTIME_E2E_PROBE||"");
  if(!expected)return json({ok:false,error:"NOT_FOUND"},404);
  const supplied=req.headers.get("x-maintenance-e2e-probe")||"";
  if(!constantTimeEqual(expected,supplied))return json({ok:false,error:"UNAUTHORIZED"},401);
  const control=await probeAiGatewayControl(env);
  const ok=control.ok&&control.binding&&control.broker_rpc&&control.routes_readable;
  return json({ok,selftest:"maintenance-ai-gateway-control-v1",service:SERVICE,ai_gateway_control:{binding:control.binding,broker_rpc:control.broker_rpc,routes_readable:control.routes_readable,error_code:control.error_code},production_worker_mutated:false,production_worker_traffic_changed:false,dynamic_route_mutation:false,secrets_redacted:true},ok?200:502)
}
export default{async fetch(req,env){const u=new URL(req.url);if(req.method==="GET"&&u.pathname==="/health"){const l=await ss(env,"/latest"),diagnostic=Boolean(String(env.MAINTENANCE_RUNTIME_E2E_PROBE||"").trim());return json({ok:true,status:"ready",service:SERVICE,api_version:API_VERSION,last_check:l.latest||null,...(diagnostic?{runtime_secret_presence:runtimeSecretPresence(env)}:{})})}if(req.method==="GET"&&u.pathname==="/v1/maintenance/latest")return json(await ss(env,"/latest"));if(req.method==="GET"&&u.pathname==="/v1/maintenance/policy")return json({ok:true,service:SERVICE,api_version:API_VERSION,policy:POLICY});if(req.method==="GET"&&u.pathname==="/v1/maintenance/runtime-selftest")return runtimeSelftest(req,env);return json({ok:false,error:"READ_ONLY"},403)},async scheduled(controller,env,ctx){ctx.waitUntil(run(env,"scheduled"))}};
export class MaintenanceState{constructor(state){this.state=state}async fetch(req){const u=new URL(req.url),s=this.state.storage,j=async()=>{try{return await req.json()}catch{return{}}};if(req.method==="GET"&&u.pathname==="/latest")return json({ok:true,latest:await s.get("latest")||null});if(req.method==="POST"&&u.pathname==="/latest"){const b=await j();await s.put("latest",b);return json({ok:true})}if(req.method==="POST"&&u.pathname==="/acquire"){const b=await j(),x=await s.get("lock");if(x&&x.expires>Date.now()&&x.owner!==b.owner)return json({ok:false,error:"BUSY"},409);const l={owner:String(b.owner||""),expires:Date.now()+600000};await s.put("lock",l);return json({ok:true,lock:l})}if(req.method==="POST"&&u.pathname==="/release"){const b=await j(),x=await s.get("lock");if(!x)return json({ok:true,released:false});if(x.owner!==b.owner)return json({ok:false,error:"LOCK_OWNER_MISMATCH",active:x},409);await s.delete("lock");return json({ok:true,released:true})}return json({ok:false,error:"NOT_FOUND"},404)}}
