import assert from "node:assert/strict";
import {baseWorkerName,buildReceipt,extractSignal,observerUrl,publishWorkersDevReceipt,receiptWorkerName,renderReceiptWorker} from "./cloudflare-workersdev-receipt.mjs";
const env={WORKERS_CI_COMMIT_SHA:"a".repeat(40),WORKERS_CI_BUILD_UUID:"build-123",WRANGLER_CI_OVERRIDE_NAME:"maintenance-worker",SOME_OTHER:"ok"};
const signal={};extractSignal('{"event":"L2_LOCAL_ROUTE_CANDIDATE_PHASE","phase":"route-family-accepted","acceptance_phase":"predeploy-control-plane"}',signal);
const receipt=buildReceipt({scope:"maintenance",mode:"preview",state:"failure",signal:{...signal,exit_code:1},env});
assert.equal(baseWorkerName("maintenance"),"maintenance-worker");assert.equal(receiptWorkerName("maintenance"),"maintenance-worker-receipt");assert.equal(observerUrl("maintenance"),"https://maintenance-worker-receipt.a15280020511.workers.dev");
const src=renderReceiptWorker(receipt);assert.ok(src.includes(receipt.receipt_digest));assert.ok(src.includes("predeploy-control-plane"));
let captured=null;const fakeRunner=(cmd,args,opts)=>{captured={cmd,args,opts};return {status:0,stdout:"",stderr:""}};const result=publishWorkersDevReceipt({scope:"maintenance",mode:"preview",state:"failure",signal:{...signal,exit_code:1},env,runner:fakeRunner});
assert.equal(result.ok,true);assert.deepEqual(captured.args.slice(0,5),["--yes","wrangler@4.123.0","deploy","--env","receipt"]);assert.equal(captured.opts.env.WRANGLER_CI_OVERRIDE_NAME,"maintenance-worker");
console.log(JSON.stringify({ok:true,suite:"cloudflare-workersdev-environment-receipt-contract",no_new_secret:true,official_wrangler_environment:true,connected_worker_name_preserved:true,secrets_redacted:true}));
