import assert from "node:assert/strict";
import {candidateTag,diagnosticAdminVersionConfig,isRelevantPath,relevantPaths,shouldRunL2,validateInvocation,validatePostAllowScript,validateWranglerVersion,wranglerCommand} from "./cloudflare-worker-gate.mjs";
const previewEnv={WORKERS_CI:"1",WORKERS_CI_BRANCH:"feature/gate",WORKERS_CI_COMMIT_SHA:"a".repeat(40)};
const deployEnv={...previewEnv,WORKERS_CI_BRANCH:"main"};
assert.deepEqual(validateInvocation("admin","preview",previewEnv),{branch:"feature/gate",sha:"a".repeat(40)});
assert.deepEqual(validateInvocation("governance","deploy",deployEnv),{branch:"main",sha:"a".repeat(40)});
assert.throws(()=>validateInvocation("admin","deploy",previewEnv),/PRODUCTION_BRANCH_REQUIRED/);
assert.throws(()=>validateInvocation("admin","preview",deployEnv),/PREVIEW_BRANCH_REQUIRED/);
assert.throws(()=>validateInvocation("unknown","preview",previewEnv),/UNSUPPORTED_SCOPE/);
assert.throws(()=>validateInvocation("admin","preview",{...previewEnv,WORKERS_CI:"0"}),/WORKERS_CI_REQUIRED/);
assert.equal(validateWranglerVersion("4.123.0"),"4.123.0");
assert.throws(()=>validateWranglerVersion("^4.123.0"),/EXACT_WRANGLER_VERSION_REQUIRED/);
assert.equal(candidateTag("a".repeat(40)),"aaaaaaaaaaaa");
assert.throws(()=>candidateTag("bad"),/VALID_CANDIDATE_TAG_REQUIRED/);
const sourceConfig={exports:{AdminCoordinator:{type:"durable-object",storage:"sqlite"}},migrations:[{tag:"v1",new_sqlite_classes:["AdminCoordinator"]}],durable_objects:{bindings:[{name:"ADMIN_COORDINATOR",class_name:"AdminCoordinator"}]},secrets:{required:["ADMIN_GPT_TOKEN","CF_API_TOKEN"]},services:[{binding:"MAINTENANCE_CONTROL",service:"maintenance-worker"}]};
const diagnosticConfig=diagnosticAdminVersionConfig(sourceConfig);
assert.equal(Object.prototype.hasOwnProperty.call(diagnosticConfig,"exports"),false);
assert.equal(Object.prototype.hasOwnProperty.call(diagnosticConfig,"migrations"),false);
assert.equal(Object.prototype.hasOwnProperty.call(diagnosticConfig,"secrets"),false);
assert.deepEqual(diagnosticConfig.durable_objects,sourceConfig.durable_objects);
assert.deepEqual(diagnosticConfig.services,sourceConfig.services);
assert.deepEqual(sourceConfig.secrets.required,["ADMIN_GPT_TOKEN","CF_API_TOKEN"]);
assert.equal(validatePostAllowScript("maintenance","preview",null),null);
assert.throws(()=>validatePostAllowScript("maintenance","preview","scripts/run-immediate-refresh.mjs"),/POST_ALLOW_SCRIPT_NOT_ALLOWED/);
assert.deepEqual(wranglerCommand("admin","preview","4.123.0","aaaaaaaaaaaa","/tmp/admin-diagnostic.jsonc"),["--yes","wrangler@4.123.0","versions","upload","--tag","aaaaaaaaaaaa","--message","PR candidate aaaaaaaaaaaa","--config","/tmp/admin-diagnostic.jsonc"]);
assert.throws(()=>wranglerCommand("admin","preview","4.123.0","aaaaaaaaaaaa",null),/ADMIN_DIAGNOSTIC_CONFIG_REQUIRED/);
for(const scope of["governance","maintenance"]){assert.deepEqual(wranglerCommand(scope,"preview","4.123.0","aaaaaaaaaaaa"),["--yes","wrangler@4.123.0","deploy","--dry-run"])}
assert.deepEqual(wranglerCommand("admin","deploy","4.123.0"),["--yes","wrangler@4.123.0","deploy"]);
assert.equal(shouldRunL2("admin","preview",["admin/l2-acceptance-request.json"]),true);
assert.equal(shouldRunL2("admin","preview",["admin/src/index.js"]),false);
assert.equal(shouldRunL2("maintenance","preview",["admin/l2-acceptance-request.json"]),false);
assert.equal(shouldRunL2("admin","deploy",["admin/l2-acceptance-request.json"]),false);
assert.equal(isRelevantPath("admin","admin/l2-acceptance-request.json"),true);
assert.equal(isRelevantPath("maintenance","scripts/cloudflare-worker-gate.mjs"),true);
assert.equal(isRelevantPath("maintenance","admin/l2-acceptance-request.json"),false);
assert.deepEqual(relevantPaths("governance",["admin/a.js","governance/z.js","governance/a.js","governance/a.js"]),["governance/a.js","governance/z.js"]);
console.log(JSON.stringify({ok:true,suite:"cloudflare-worker-gate-contract",fail_closed_context:true,exact_wrangler_pin:true,per_worker_path_isolation:true,build_side_effect_post_hooks_disabled:true,admin_preview_diagnostic_version_upload:true,admin_durable_object_binding_preserved:true,admin_required_secret_validation_bypassed_for_probe:true,admin_remote_secret_values_unchanged:true,admin_lifecycle_mutation_removed_from_version_upload:true,governance_preview_compile_only:true,maintenance_preview_compile_only:true,l2_requires_explicit_admin_trigger_path:true,l2_only_runs_in_admin_preview:true}));
