import assert from "node:assert/strict";
import {candidateTag,isRelevantPath,relevantPaths,shouldRunL2,validateInvocation,validatePostAllowScript,validateWranglerVersion,wranglerCommand} from "./cloudflare-worker-gate.mjs";
const previewEnv={WORKERS_CI:"1",WORKERS_CI_BRANCH:"feature/gate",WORKERS_CI_COMMIT_SHA:"a".repeat(40)};
const deployEnv={...previewEnv,WORKERS_CI_BRANCH:"main"};
assert.deepEqual(validateInvocation("admin","preview",previewEnv),{branch:"feature/gate",sha:"a".repeat(40)});
assert.deepEqual(validateInvocation("governance","deploy",deployEnv),{branch:"main",sha:"a".repeat(40)});
assert.throws(()=>validateInvocation("admin","deploy",previewEnv),/PRODUCTION_BRANCH_REQUIRED/);
assert.throws(()=>validateInvocation("admin","preview",deployEnv),/PREVIEW_BRANCH_REQUIRED/);
assert.throws(()=>validateInvocation("unknown","preview",previewEnv),/UNSUPPORTED_SCOPE/);
assert.throws(()=>validateInvocation("admin","preview",{...previewEnv,WORKERS_CI:"0"}),/WORKERS_CI_REQUIRED/);
assert.equal(validateWranglerVersion("4.123.0"),"4.123.0");
assert.throws(()=>validateWranglerVersion("^4.123.0"),/EXACT_WRANGLER_VERSION_REQUIRED/);
assert.equal(candidateTag("a".repeat(40)),"aaaaaaaaaaaa");
assert.throws(()=>candidateTag("bad"),/VALID_CANDIDATE_TAG_REQUIRED/);
assert.equal(validatePostAllowScript("maintenance","preview",null),null);
assert.throws(()=>validatePostAllowScript("maintenance","preview","scripts/run-immediate-refresh.mjs"),/POST_ALLOW_SCRIPT_NOT_ALLOWED/);
for(const scope of["admin","governance","maintenance"]){assert.deepEqual(wranglerCommand(scope,"preview","4.123.0"),["--yes","wrangler@4.123.0","deploy","--dry-run"])}
assert.deepEqual(wranglerCommand("admin","deploy","4.123.0"),["--yes","wrangler@4.123.0","deploy"]);
assert.equal(shouldRunL2("maintenance","preview",["maintenance/l2-acceptance-request.json"]),true);
assert.equal(shouldRunL2("maintenance","preview",["maintenance/src/index.js"]),false);
assert.equal(shouldRunL2("admin","preview",["maintenance/l2-acceptance-request.json"]),false);
assert.equal(shouldRunL2("maintenance","deploy",["maintenance/l2-acceptance-request.json"]),false);
assert.equal(isRelevantPath("maintenance","maintenance/l2-acceptance-request.json"),true);
assert.equal(isRelevantPath("admin","scripts/cloudflare-worker-gate.mjs"),true);
assert.equal(isRelevantPath("admin","maintenance/l2-acceptance-request.json"),false);
assert.deepEqual(relevantPaths("governance",["admin/a.js","governance/z.js","governance/a.js","governance/a.js"]),["governance/a.js","governance/z.js"]);
console.log(JSON.stringify({ok:true,suite:"cloudflare-worker-gate-contract",fail_closed_context:true,exact_wrangler_pin:true,per_worker_path_isolation:true,build_side_effect_post_hooks_disabled:true,all_preview_workers_compile_dry_run_only:true,l2_requires_explicit_maintenance_trigger_path:true,l2_only_runs_in_maintenance_preview:true,worker_preview_deployment_mutation:false}));
